export interface RoadmapItem {
  version: string;
  title: string;
  description: string;
  features?: string[];
  status: 'DONE' | 'NEXT' | 'LATER';
}

export const USER_ROADMAP: RoadmapItem[] = [
  { version: '0.2.1', title: 'Aktualizacje planu studiów', description: 'Porównywanie nowych wersji planu, profil grup i bezpieczne poprawki serii.', status: 'DONE' },
  { version: '0.2.2', title: 'Stabilniejszy import planu', description: 'Lepsza odporność na różne układy XLSX, formaty dat, godzin i grup oraz czytelniejsza diagnostyka.', status: 'DONE' },
  { version: '0.2.3', title: 'Rozszerzenia kalendarza', description: 'Wydarzenia wielodniowe, całodniowe i ręczne serie na kilku wybranych datach.', features: ['wydarzenia wielodniowe', 'zaznaczanie kilku dni', 'wydarzenia całodniowe', 'ręczne serie wielu dat'], status: 'DONE' },
  { version: '0.2.4', title: 'Bezpieczeństwo danych', description: 'Cofanie, Kosz, historia zmian, punkty przywracania, backup oraz bezpieczne podglądanie innych grup.', features: ['Cofnij', 'Kosz', 'restore points', 'lokalny backup', 'dni bez automatycznej dyspozycyjności', 'profile podglądowe grup'], status: 'DONE' },
  { version: '0.3.0', title: 'Grafik pracy PDF', description: 'Lokalny import rzeczywistego grafiku pracy, profil miejsca pracy, godziny, kolizje i opcjonalny podgląd zespołu na zmianie.', features: ['import PDF', 'potwierdzone zmiany', 'podsumowanie godzin', 'kto jest ze mną na zmianie'], status: 'DONE' },
  { version: '0.3.1', title: 'Model dnia i spójność kalendarza', description: 'Cel godzin pracy, codzienne czynności, kolory kategorii, wykrywanie konfliktów i bezpieczne korekty planu.', features: ['Centrum niespójności', 'nakładanie godzin', 'korekta pojedynczego terminu lub serii', 'kolory STUDY / WORK / PERSONAL / OTHER'], status: 'DONE' },
  { version: '0.3.2', title: 'Automatyczna dyspozycyjność', description: 'Jeden rekomendowany plan tygodnia wyliczany wokół zajęć, pracy i ograniczeń.', features: ['krótkie 1-2 h okna', 'potwierdzona praca ma pierwszeństwo', 'Akceptuj / Edytuj / Odrzuć', 'Dlaczego?', 'kopiowanie dyspozycyjności'], status: 'DONE' },
  { version: '0.3.3', title: 'Prostsza Praca + dyspozycja vs grafik', description: 'Minimalistyczny moduł Praca, odchudzone Ustawienia i dokładne porównanie wysłanej dyspozycyjności z finalnym grafikiem PDF.', features: ['Grafik / Dyspozycyjność', 'ustawienia przy Pracy', 'godziny poza dyspozycyjnością', 'read-only comparison'], status: 'DONE' },
  { version: '0.3.3-hotfix.1', title: 'Ręczna i automatyczna dyspozycyjność', description: 'Wyjątki dnia i własne godziny bezpośrednio w Kalendarzu; optimizer uzupełnia tylko brakujące godziny.', features: ['od / do dla dnia', 'wykluczanie godzin', 'ręczna dyspozycyjność', 'uzupełnij brakujące godziny'], status: 'DONE' },
  { version: '0.3.3-hotfix.2', title: 'Kalendarzowy podgląd innej grupy', description: 'Bezpieczny podgląd planu koleżanki w lekkim kalendarzu miesięcznym z opcjonalnym widokiem listy.', features: ['Kalendarz / Lista', 'szczegóły dnia', 'zmiana miesiąca', 'pełna izolacja od własnego planu'], status: 'DONE' },
  { version: '0.3.3-hotfix.3', title: 'Dyspozycyjność z kalendarza bez ręcznego startu', description: 'Optimizer sam wylicza godziny z aktualnego kalendarza; od/do są tylko opcjonalnymi wyjątkami dnia.', features: ['automat bez DayRule', 'opcjonalne od / do', 'ręczny blok tylko na życzenie', 'standardowe ramy pracy'], status: 'DONE' },
  { version: '0.3.3-hotfix.4', title: 'Czytelniejsze zmiany i zespół', description: 'Lepsza hierarchia własnej zmiany, osobne wiersze współpracowników i czytelny wspólny czas.', features: ['Twoja zmiana', 'Razem z Tobą', 'sortowanie po wspólnym czasie', 'zwijanie długiej listy'], status: 'DONE' },
  { version: '0.3.4', title: 'Podsumowanie pracy', description: 'Lekkie miesięczne podsumowanie godzin, zmian i zgodności z wysłaną dyspozycyjnością.', features: ['godziny w miesiącu', 'zmiany i dni pracy', 'godziny tygodniami', 'zgodność z dyspozycyjnością'], status: 'DONE' },
  { version: '0.3.5', title: 'Lista zakupów', description: 'Jedna szybka lokalna lista z odhaczaniem, opcjonalną ilością i backupem.', status: 'DONE' },
  { version: '0.3.6', title: 'Przenoszenie danych', description: 'Eksport i import całego stanu aplikacji między urządzeniami przez jeden plik, bez konta i chmury.', features: ['jeden plik JSON', 'podgląd przed importem', 'checksum', 'restore point przed zastąpieniem'], status: 'DONE' },
  { version: '0.3.7', title: 'Domknięcie UX i stabilności', description: 'Czytelne zablokowane akcje, mobile, trwałość danych i końcowy audit przepływów 0.3.x.', features: ['wyjaśnione blokady', 'mobile audit', 'persistent storage', 'PWA polish'], status: 'DONE' },
  { version: '0.4.0', title: 'Cykl', description: 'Minimalistyczny prywatny tracker miesiączek z własną historią, lokalnym modelem szacowania i ochroną danych.', features: ['Dzisiaj / Kalendarz / Historia', 'uczciwe zakresy', 'przerwy w obserwacji', 'backup i transfer'], status: 'DONE' },
  { version: '0.4.1', title: 'Trasa do miejsc', description: 'Szybkie otwieranie trasy do zapisanej lokalizacji bez Google API i bez śledzenia w tle.', status: 'DONE' },
  { version: '0.5.0', title: 'Historyczny fundament powiadomień', description: 'Powstał planner i eksperymentalny Web Push. Warstwa serwerowa została później świadomie wycofana przed finalnym 1.0.0; lokalny planner/preferencje zostają pod przyszły Android.', features: ['planner reminderów', 'preferencje lokalne', 'historia Web Push zachowana w Git'], status: 'DONE' },
  { version: '0.5.1', title: 'Subtelne tło kwiatowe', description: 'Lekki motyw dekoracyjny z trybem statycznym, delikatną animacją i pełnym wyłączeniem bez wpływu na funkcje aplikacji.', features: ['Wyłączone / Statyczne / Delikatnie animowane', 'prefers-reduced-motion', 'bez nowych zależności'], status: 'DONE' },
  { version: '0.5.2', title: 'Dopracowanie tła kwiatowego', description: 'Bogatsza, nadal subtelna kompozycja kwiatowa z mniejszą gęstością na mobile i niesynchronizowanym ruchem tylko wybranych elementów.', features: ['7 grup desktop', 'uproszczony mobile', '3 wolne animacje', 'bez zmian funkcjonalnych'], status: 'DONE' },
  { version: '0.5.3', title: 'Dopracowanie nawigacji i ikon', description: 'Spójne ikony SVG wspierają osiem istniejących nazw sekcji bez przebudowy sidebaru i mobilnego paska.', features: ['ikona + tekst', '8 istniejących sekcji', 'mobile horizontal scroll', 'bez nowych zależności'], status: 'DONE' },
  { version: '0.5.4', title: 'Kwiatowy motyw przewodni UI', description: 'Wyraźniejsza, spójna tożsamość kwiatowa całej aplikacji z jednym globalnym wyłączeniem i bez obciążania kart oraz formularzy.', features: ['pełne Wyłączone / Statyczne / Delikatnie animowane', 'wspólne floral accents', 'bez nowych zależności'], status: 'DONE' },
  { version: '0.6.0', title: 'Dziennik Cyklu', description: 'Minimalistyczne dzienne dane wspierające własną historię bez diagnozowania: krwawienie, ból, samopoczucie i krótka notatka.', features: ['szybki wpis dnia', 'mało pól', 'local-first', 'bez diagnoz'], status: 'DONE' },
  { version: '0.6.1', title: 'Własne wzorce Cyklu', description: 'Minimalistyczne podsumowanie własnej historii: typowa długość miesiączki i najczęściej zapisane obserwacje, bez wykresów, diagnoz i trwałych statystyk.', status: 'DONE' },
  { version: '0.6.2', title: 'Dziennik Cyklu - lek przeciwbólowy', description: 'Jedno opcjonalne Tak / Nie w dziennym wpisie, bez listy leków, dawek, reminderów i porad medycznych.', status: 'DONE' },
  { version: '0.6.3', title: 'Szacowane okno owulacji', description: 'Ostrożny zakres szacunkowy tylko przy stabilnej prognozie Cyklu, bez bezpiecznych dni i bez zastosowania antykoncepcyjnego.', status: 'DONE' },
  { version: '0.7.0', title: 'Globalne wyszukiwanie', description: 'Szybkie lokalne wyszukiwanie wydarzeń, miejsc, Studiów i Pracy bez rozbudowy głównej nawigacji i bez indeksowania danych Cyklu.', status: 'DONE' },
  { version: '1.0.0-rc.1', title: 'Release Candidate', description: 'Pierwszy finalny audit i poprawki wydaniowe bez nowych funkcji; finalne 1.0.0 pozostaje zablokowane do pełnych testów i deploymentu.', status: 'DONE' },
  { version: '1.0.0-rc.2', title: 'Release Candidate - local check hotfix', description: 'Minimalne poprawki zależności i TypeScript ujawnione przez rzeczywisty lokalny npm check; bez nowych funkcji. Pełny local check wymaga jeszcze potwierdzenia po npm ci w środowisku z dostępem do npm.', status: 'DONE' },
  { version: '1.0.0-rc.3', title: 'Release Candidate - test-suite hotfix', description: 'Minimalna aktualizacja starych testów migracji, backupu, reminderów i izolacji IndexedDB po lokalnym wyniku 326/336 PASS; bez zmian funkcjonalnych.', status: 'DONE' },
  { version: '1.0.0-rc.4', title: 'Release Candidate - zgodność PDF.js', description: 'Ultra-mały hotfix typów PDF.js i finalizacja lokalnej bramki npm check; bez zmian funkcjonalnych.', status: 'DONE' },
  { version: '1.0.0-rc.5', title: 'Release Candidate - security PDF.js', description: 'Minimalna aktualizacja pdfjs-dist do naprawionej wersji 6.2.108; bez nowych funkcji i bez rozszerzania importu PDF.', status: 'DONE' },
  { version: '1.0.0-rc.6', title: 'Release Candidate - zgodność PDF.js 6 cleanup', description: 'Jednowierszowa zgodność cleanup PDF.js 6 oraz stabilna końcowa bramka dwóch kolejnych checków; bez nowych funkcji.', status: 'DONE' },
  { version: '1.0.0-rc.7', title: 'Release Candidate - deterministyczny Change Journal', description: 'Minimalna stabilizacja kolejności Change Journal i regresje Undo po powtarzalnym sporadycznym FAIL; bez nowych funkcji i bez zmiany schema.', status: 'DONE' },
  { version: '1.0.0', title: 'Stabilne wydanie GitHub-only', description: 'Pierwsze stabilne wydanie PWA bez backendu: GitHub Pages, offline, dane lokalne, PDF/XLSX i bezpieczny transfer danych.', features: ['GitHub Pages', 'PWA offline', 'local-first', 'bez backendu'], status: 'DONE' },
  { version: '1.0.1', title: 'Czytelniejsza nawigacja i zespół pracy', description: 'Małe poprawki codziennej obsługi: wygodniejsza kolejność sekcji oraz pełny i responsywny skład współpracowników w Dziś i szczegółach dnia.', features: ['kolejność nawigacji', 'pełny zespół w Dziś', 'pełny zespół w wybranym dniu', 'czytelne długie nazwiska'], status: 'DONE' },
  { version: '1.1.0', title: 'Aplikacja Android i lokalne powiadomienia', description: 'Opcjonalny kolejny etap: ten sam kod aplikacji w kontenerze Android z przypomnieniami planowanymi lokalnie na urządzeniu, bez Cloudflare i bez Web Push.', features: ['Android', 'lokalne powiadomienia systemowe', 'Data Transfer z PWA', 'bez backendu'], status: 'LATER' },
];
